name: Deploy Website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6.0.2
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test Code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    # script-file: ${{ steps.publish.outputs.nothing-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v6.0.2
      - name: Install dependencies
        run: npm ci
      - name: Build Website
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
     #  run: find dist/assets/*.js -type f -execdir echo 'nothing-file={}' >> $GITHUB_OUTPUT ';'
     #  run: find dist/assets/*.js -type f -execdir echo '::set-output name=script-file::{}' ';'
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: dist-files
          path: dist
        # path: |
        #   dist
        #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: dist-files
      - name: Output Contents
        run: ls
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying......."
